### ISSUE TITLE
Support ZNC 1.6.0

### ISSUE THREAD

**Issue by MarcusHogue** [cocodelabs/znc-palaver#20]
I'm trying to compile the module on OS X for ZNC 1.6 and getting the following errors with it failing to compile:
```
/usr/local/Cellar/znc/1.6.0/include/znc/ZNCString.h:85:47: error: expected a class or namespace
        static const CaseSensitivity CaseSensitive = CaseSensitivity::CaseSensitive;
                                                     ^
/usr/local/Cellar/znc/1.6.0/include/znc/ZNCString.h:86:49: error: expected a class or namespace
        static const CaseSensitivity CaseInsensitive = CaseSensitivity::CaseInsensitive;
                                                       ^
```

**Comment by kylef** [comment]
Hi @MarcusHogue,

Thanks for reporting, this seems like a bug in ZNC itself. I'm going to try hunt it down and fix it.

**Comment by lvialle** [comment]
In order to compile, you need to edit ZNCString.h from your ZNC installation and change le lines 85-86 to:
	static const CaseSensitivity CaseSensitive = CaseSensitive;
	static const CaseSensitivity CaseInsensitive = CaseInsensitive;

**Comment by bradleysepos** [comment]
cocodelabs/znc-palaver@f159c78 (latest) and znc/znc@f47e846 (1.6.0) appear to build without modifications on OS X 10.10.4 / Xcode 6.4. Suggest closing this issue.

**Comment by kylef** [comment]
Thanks @bradleysepos
