### ISSUE TITLE
Devices refuse to register

### ISSUE THREAD

**Issue by delica** [cocodelabs/znc-palaver#21]
I lost push notifications on Wednesday 11th March. In my attempt to fix this I have reinstalled the app on my devices, recompiled the module (first for ZNC 1.0, then after upgrading to ZNC 1.6), tried the Notifications On/Off thing in Settings.app, all to no avail. Whatever I do, the devices refuse to register with the module, and I get the following response from within Palaver.app itself:

There are no devices registered with this server.
You are not connected from a Palaver client.

Wondering now if this is an iOS 8.2 issue?

**Comment by emagaliff** [comment]
Having the same issue. See IRC log for details: http://pastebin.com/KRNgaEVt

**Comment by glyph** [comment]
Same issue here as well.  Unlucky that this was my first time trying to get palaver to do this, I was tearing my hair out trying to figure out how I'd misconfigured the module.

**Comment by kylef** [comment]
Hi all, sorry about this. Not entirely sure what happened, various push notification certificates were revoked and I had to rebuild them.

Push notifications should work now, please let me know if you are facing any other issues.

Regards

**Comment by glyph** [comment]
@kylef - `/msg *palaver list` still tells me "There are no devices registered with this server. You are not connected from a Palaver client."  I disconnected and reconnected.  Is there anything else I need to do with the client to tell it to identify itself to the server with the appropriate capability?

**Comment by glyph** [comment]
Right now, I am on ZNC 1.6, running in a Docker image based on Ubuntu Vivid, but before @kylef's update I was running ZNC 1.2, then 1.4, with the same behavior, upgrading trying to fix it :).

**Comment by delica** [comment]
Thank you, @kylef, but devices are still refusing to register, neither an iPhone 5 or an iPhone 6, both on iOS8. I have tried again reinstalling the app, and reinstalling the module, notification on/off/on, but nothing is persuading the app to register with the module.

**Comment by glyph** [comment]
The thing that ended up fixing it for me was disabling and then re-enabling notifications in the Settings app.  Moments after doing so, without even reconnecting, it identified my client as Palaver.

**Comment by delica** [comment]
Well, no matter what I do I can't get any devices to register. I am pretty much at a loss.

**Comment by TiiRex9** [comment]
I still have the same problem. Currently I'm running the lates iOS 9 beta. But I'm pretty sure, that this problem was there before. Also the latest Palaver iOS App and I just updated to the latest ZNC 1.6.1 Version and compiled the latest znc-palaver module. But sadly my devices won't register to the module. I still have three old devices in the list. I use an iPhone 6.

**Comment by bizmurr** [comment]
Getting the same thing as well on iOS 9, will this be fixed in 2.2?

**Comment by kylef** [comment]
@bizmurr, This should be fixed in Palaver 2.2.

**Comment by kylef** [comment]
Palaver 2.2 is now out, please sends us a support email (support@palaverapp.com) if you're still having difficulties with Palaver 2.2.
