### ISSUE TITLE
Failure to compile under Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by prenetic** [cocodelabs/znc-palaver#23]
Upon updating to ZNC 1.6.0 I observed the Palaver module was preventing ZNC from starting (oops!). Removed the module temporarily and began pulling the latest to compile and install. Using the latest ZNC package from the teward/znc PPA. Unable to compile.

```
mcoppola@host2:~$ rm -rf znc-palaver/
mcoppola@host2:~$ git clone https://github.com/Palaver/znc-palaver
Cloning into 'znc-palaver'...
remote: Counting objects: 93, done.
remote: Total 93 (delta 0), reused 0 (delta 0), pack-reused 93
Unpacking objects: 100% (93/93), done.
Checking connectivity... done.
mcoppola@host2:~$ cd znc-palaver
mcoppola@host2:~/znc-palaver$ make
Building "palaver.so" for ZNC 1.6.0... In file included from /usr/include/znc/Socket.h:21:0,
                 from /usr/include/znc/HTTPSock.h:21,
                 from /usr/include/znc/WebModules.h:22,
                 from /usr/include/znc/Modules.h:21,
                 from palaver.cpp:11:
/usr/include/znc/Csocket.h:83:27: fatal error: unicode/ucnv.h: No such file or directory
 # include <unicode/ucnv.h>
                           ^
compilation terminated.
[ !! ] Error while building "palaver.so"
make: *** [palaver.so] Error 1
```

**Comment by z0rc** [comment]
This is due to znc-dev from PPA still missing the libicu-dev in dependencies list. Just do `apt-get install libicu-dev`, the module should compile afterwards.

cc @teward

**Comment by teward** [comment]
@z0rc ACK on the needed dep - I'll have to forward this to Debian as well as it's Patrick Matthai's packaging in use in the PPA as well.

**Comment by prenetic** [comment]
Totally worked. Thanks all.

**Comment by teward** [comment]
There's a bug on this now on Launchpad, where I track bugs in the PPAs I maintain for the public.  https://bugs.launchpad.net/teward-ppas/+bug/1445163 is the bug.  Comments are welcome there, but I'll get to it as soon as I can.

**Comment by kylef** [comment]
I'm going to close this issue because it's a distro problem and not a problem with this module.
