### ISSUE TITLE
Add support for new channel message notifications

### ISSUE THREAD

**Issue by bizmurr** [cocodelabs/znc-palaver#27]
It would be great if this had the option to send notifications on any new messages in a specific channel.

**Comment by kylef** [comment]
Thanks for the request @bizmurr, this has actually already been added to Palaver 2.2 which should be out soon.

<img src="https://cloud.githubusercontent.com/assets/44164/9981924/cc22718e-5f7f-11e5-9df2-97589f757ccd.PNG" width=375 height=667 alt="Palaver Channel Settings" />
