### ISSUE TITLE
Push notifications for server notices

### ISSUE THREAD

**Issue by praseodym** [cocodelabs/znc-palaver#32]
After updating the plugin I get push notifications for server notices, is there any way to disable this behaviour?

**Comment by kylef** [comment]
I've made an update to the module to exclude NOTICEs from being sent as push notifications for connection information before you're fully authenticated (https://github.com/cocodelabs/znc-palaver/pull/40).

We will add options to a future version of Palaver to control NOTICEs.

If other NOTICEs are still a problem after the above change for you right now, I'd suggest just commenting out / deleting a couple of lines from the module to disable NOTICE push messages.

You can remove the lines at https://github.com/cocodelabs/znc-palaver/blob/d9aff6bce72bcf38775fafe26043b28c08338b05/palaver.cpp#L1084-L1096 and rebuilt the module. Once you can change the behaviour in Palaver, you can go back to using the original module.

Regards,

Kyle
