### ISSUE TITLE
Build Failure, OS X 10.11.2

### ISSUE THREAD

**Issue by ForumFerret** [cocodelabs/znc-palaver#35]
Getting an error during build as follows: 

-------

<prompt>$ make
Building "palaver.so" for ZNC 1.0... In file included from palaver.cpp:15:
In file included from /usr/local/Cellar/znc/1.0/include/znc/Modules.h:13:
In file included from /usr/local/Cellar/znc/1.0/include/znc/WebModules.h:13:
In file included from /usr/local/Cellar/znc/1.0/include/znc/Template.h:13:
/usr/local/Cellar/znc/1.0/include/znc/Utils.h:188:10: fatal error: 
      'openssl/blowfish.h' file not found
#include <openssl/blowfish.h>
         ^
1 error generated.
[ !! ] Error while building "palaver.so"
make: *** [palaver.so] Error 1

**Comment by kylef** [comment]
This seems to be a problem with your ZNC install / openssl. The error is coming from the ZNC header `znc/Utils.h` referencing `openssl/blowfish.h`. Did you remove `openssl` after you built ZNC?

**Comment by ForumFerret** [comment]
Not intentionally!

Could it be fixed by going into my znc directory and doing git clone again?

**Comment by kylef** [comment]
I'd try rebuilding ZNC and then trying to build the module again.
