### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by arielelkin** [cocodelabs/znc-palaver#46]
Would it be possible to have a Docker image for ZNC Palaver?

**Comment by kylef** [comment]
@arielelkin There is already one available on Docker Hub: https://hub.docker.com/r/palaver/znc-palaver/

There are some usage instructions at: https://gist.github.com/kylef/cf3b41f7771732d8f159312a2e28d6c0

It's kinda "use at your own risk" and no support given though. Would only recommend using it if you really know how to use Docker.

**Comment by kylef** [comment]
I'm going to close this now, ZNC provides docker images in https://hub.docker.com/_/znc/ which you can use the module in conjunction with. As per ZNC docker instructions, you need to place palaver.cpp from znc-palaver into the modules directory:

> If you use any external module, put the .cpp, .py or .pm file to /znc-data/modules (you may need to create that directory).
