### ISSUE TITLE
Push notifications again not working

### ISSUE THREAD

**Issue by kbembedded** [cocodelabs/znc-palaver#48]
I cant reopen a closed issues, so I thought I would make more noise.  Push notifications are not working again.  See #47.

**Comment by kylef** [comment]
Hi @kbembeddedb sorry I did not see this sooner. I assume that the problem has been solved by then?

In future, you are usually better off emailing us at our support channel (support@palaverapp.com), this creates a ticket in our system and easier to track so it doesn't get forgotten.

Regards,

Kyle

**Comment by kbembedded** [comment]
Yes, it appears to be working now.
