### ISSUE TITLE
Only receive push notification when Palaver app is online

### ISSUE THREAD

**Issue by subsevenx2001** [cocodelabs/znc-palaver#57]
Hello,

I have set up ZNC server and palaver plugin. I expect that I can receive push notifications  when I'm away or disconnected. However, it seems that I cannot receive push notifications from the module. I've tried znc --debug, and the push module does send message with status code 202 according to debug logs. And I also tried /msg *palaver list and it does show my iphone.

Is there any other setting needed to receive push notifications when I'm offline?

**Comment by iamDecode** [comment]
Push notifications are *only* showed if you are offline; the notifications that you are seeing are probably local notifications instead. We are not currently experiencing any issues with the push service, so I am not quite sure what might cause this. You could try toggling push notifications off and on again in the settings. This will refresh your push tokens and perhaps resolve the issue. If this does not help, please provide us with some more information (e.g., the exact time you sent the message) such that we can match it events on the server side.

**Comment by kylef** [comment]
@subsevenx2001 if you can share the output of `/msg *palaver list` to us via email (support@palaverapp.com) that would let us debug this further.

**Comment by subsevenx2001** [comment]
Hello, sorry for late reply.
I have sent an email to support@palaverapp.com describing my situation and my device token.
Please let me know if more information is needed and thank you for help :)
