### ISSUE TITLE
Unable to load palaver: Unable to open module palaver:

### ISSUE THREAD

**Issue by teleanu** [cocodelabs/znc-palaver#74]
Any idea how to fix this?
Thank you!

`<*status> Unable to load palaver: Unable to open module palaver: /home/error/.znc/modules/palaver.so: undefined symbol: _ZN5Csock17IcuExtToUCallbackEP23UConverterToUnicodeArgsPKci24UConverterCallbackReasonP10UErrorCode`

**Comment by kylef** [comment]
From the error, it sounds like the Palaver module was compiled with a different version of ZNC than the version you are loading the module with.

ZNC modules must be compiled with the same version of ZNC. When upgrading ZNC, all modules must be re-built.

[Compiling modules](https://wiki.znc.in/Compiling_modules)

**Comment by jmooo** [comment]
Running into this because I use the official docker image of znc, but have to compile this module from source:

**Comment by kylef** [comment]
@jmooo If you're using the official ZNC container images, copy the palaver.cpp file into the `/znc-data/modules` directory, the container will automatically build it during launch as [per the ZNC documentation](https://hub.docker.com/_/znc/):

> If you use any external module, put the .cpp, .py or .pm file to /znc-data/modules (you may need to create that directory).

**Comment by jmooo** [comment]
Well that's how I got it to *build*, strictly, but ZNC is unable to load it via that method still:
> Unable to load palaver: Version mismatch for module palaver: core is 1.8.2, module is built for 1.8.x. Recompile this module.

so i'm working on hand editing CMake files because ZNC appears to be simple string checking an `1.8.2 != 1.8.x`
